### Créer un utilisateur
POST http://localhost:3102/creer
Content-Type: application/json

{
  "nom_utilisateur": "test",
  "mdp": "test123/"
}

### Se connecter
POST http://localhost:3102/me-connecter
Content-Type: application/json

{
  "nom_utilisateur": "test",
  "mdp": "test123/"
}

### Récupérer liste miels
GET http://localhost:3102/miels
Authorization: Believe eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0IiwiY3JlYXRlZEF0IjoiMjAyNS0wMS0xNlQxNDo0OTo1NC43NzZaIiwidXBkYXRlZEF0IjoiMjAyNS0wMS0xNlQxNDo0OTo1NC43NzZaIiwiaWF0IjoxNzM3MDM4OTk2fQ.IeC-07lDxdZ_viN_e-29q4gdDNICGNzWzs5bPXP2I4g
Content-Type: application/json

### Créer miel
POST http://localhost:3102/miels
Authorization: Believe eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0IiwiY3JlYXRlZEF0IjoiMjAyNS0wMS0xNlQxNDo0OTo1NC43NzZaIiwidXBkYXRlZEF0IjoiMjAyNS0wMS0xNlQxNDo0OTo1NC43NzZaIiwiaWF0IjoxNzM3MDM4OTk2fQ.IeC-07lDxdZ_viN_e-29q4gdDNICGNzWzs5bPXP2I4g
Content-Type: application/json

{
  "nom": "Miel test",
  "description": "Ceci est un miel.",
  "prix": 10
}

### Récupérer un miel
GET http://localhost:3102/miels/4
Authorization: Believe eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0IiwiY3JlYXRlZEF0IjoiMjAyNS0wMS0xNlQxNDo0OTo1NC43NzZaIiwidXBkYXRlZEF0IjoiMjAyNS0wMS0xNlQxNDo0OTo1NC43NzZaIiwiaWF0IjoxNzM3MDM4OTk2fQ.IeC-07lDxdZ_viN_e-29q4gdDNICGNzWzs5bPXP2I4g
Content-Type: application/json

### Modifier un miel
PUT http://localhost:3102/miels/2
Authorization: Believe eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0IiwiY3JlYXRlZEF0IjoiMjAyNS0wMS0xNlQxNDo0OTo1NC43NzZaIiwidXBkYXRlZEF0IjoiMjAyNS0wMS0xNlQxNDo0OTo1NC43NzZaIiwiaWF0IjoxNzM3MDM4OTk2fQ.IeC-07lDxdZ_viN_e-29q4gdDNICGNzWzs5bPXP2I4g
Content-Type: application/json

{
  "nom": "Miel tests",
  "description": "Ceci est un miel.",
  "prix": 10
}

### Supprimer un miel
DELETE http://localhost:3102/miels/3
Authorization: Believe eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0IiwiY3JlYXRlZEF0IjoiMjAyNS0wMS0xNlQxNDo0OTo1NC43NzZaIiwidXBkYXRlZEF0IjoiMjAyNS0wMS0xNlQxNDo0OTo1NC43NzZaIiwiaWF0IjoxNzM3MDM4OTk2fQ.IeC-07lDxdZ_viN_e-29q4gdDNICGNzWzs5bPXP2I4g
Content-Type: application/json

### Ajouter tag
POST http://localhost:3102/tags
Authorization: Believe eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0IiwiY3JlYXRlZEF0IjoiMjAyNS0wMS0xNlQxNDo0OTo1NC43NzZaIiwidXBkYXRlZEF0IjoiMjAyNS0wMS0xNlQxNDo0OTo1NC43NzZaIiwiaWF0IjoxNzM3MDM4OTk2fQ.IeC-07lDxdZ_viN_e-29q4gdDNICGNzWzs5bPXP2I4g
Content-Type: application/json

{
  "tag": "sapin"
}